version: '3.7'
services:
    server:
        build: .
        command:
            bash -c 'python manage.py runserver 0.0.0.0:8000'
        ports:
            - "8000:8000"
        volumes:
            -   .:/code
