# Generated by Django 4.2.2 on 2023-08-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_state_alter_customer_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.state",
            ),
        ),
    ]
