# Generated by Django 4.2.2 on 2023-06-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machinetype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
