# Generated by Django 4.2.2 on 2023-06-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machine", "0005_machine_attachment_report_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="machines"),
        ),
    ]
