# Generated by Django 4.2.2 on 2023-07-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "machine",
            "0007_alter_machine_software_version_alter_machine_vintage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="hour_active",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="machine",
            name="life_time",
            field=models.IntegerField(default=10),
        ),
    ]
